# Generated by Django 2.2.6 on 2020-05-12 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TvShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Dizi Ad')),
                ('kind', models.CharField(max_length=100, verbose_name='Tür')),
                ('issue', models.CharField(max_length=800, verbose_name='Konu')),
                ('year', models.CharField(max_length=12, verbose_name='Yıl')),
                ('director', models.CharField(max_length=70, verbose_name='Yönetmen')),
                ('performer', models.CharField(max_length=250, verbose_name='Oyuncular')),
                ('season', models.CharField(max_length=30, verbose_name='Sezon Sayısı')),
                ('imdbPoint', models.CharField(max_length=5, verbose_name='IMDB Puanı')),
                ('link', models.CharField(max_length=200, verbose_name='Fragman')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('visitors', models.IntegerField(default=0, verbose_name='Ziyaretçi Sayısı')),
                ('keywords', models.CharField(max_length=500, verbose_name='Anahtar Kelimeler')),
                ('seriesImage', models.FileField(blank=True, null=True, upload_to='', verbose_name='Dizinin Resmini Ekleyin')),
            ],
            options={
                'verbose_name_plural': 'Diziler',
                'ordering': ['kind'],
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addedDate', models.DateTimeField(auto_now_add=True)),
                ('series', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='TvShow.TvShow', verbose_name='Dizi')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name_plural': 'İzlenecekler Listesi',
                'ordering': ['-addedDate'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500, verbose_name='Yorum')),
                ('commentDate', models.DateTimeField(auto_now_add=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='TvShow.TvShow', verbose_name='Dizi')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name_plural': 'Yorumlar',
                'ordering': ['-commentDate'],
            },
        ),
    ]
